# Generated by Django 5.1.7 on 2025-09-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
    ]
