version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8005
    ports:
      - "8005:8005"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file: .env
    command: gunicorn doccure.wsgi:application --bind 0.0.0.0:8005 --workers 2 --timeout 120
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    restart: always
    build: ./deployment/nginx/
    ports:
      - "8080:80"  # Changed from 80:80 to 8080:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
