services:
  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: laso_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - laso_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Django Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: laso_web
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,65.108.91.110,host.docker.internal,*}
      - USE_SQLITE=${USE_SQLITE:-False}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_TO_FILE=${LOG_TO_FILE:-False}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "3000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - laso_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/liveness/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Celery Worker for Background Tasks
  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: laso_celery
    restart: unless-stopped
    command: celery -A laso worker -l info
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - USE_SQLITE=${USE_SQLITE:-False}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - media_volume:/app/media
      - logs_volume:/app/logs
    depends_on:
      - redis
      - web
    networks:
      - laso_network

  # Celery Beat for Scheduled Tasks
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: laso_celery_beat
    restart: unless-stopped
    command: celery -A laso beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=/tmp/celerybeat.pid
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - USE_SQLITE=${USE_SQLITE:-False}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_password}@redis:6379/0
    volumes:
      - logs_volume:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - laso_network

  # Nginx Reverse Proxy (using port 8081 to avoid conflict)
  nginx:
    image: nginx:alpine
    container_name: laso_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - laso_network

volumes:
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  logs_volume:
    driver: local

networks:
  laso_network:
    driver: bridge