# Generated by Django 5.2.1 on 2025-06-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('template_type', models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatma'), ('appointment_confirmation', 'Randevu Onayı'), ('appointment_cancellation', 'Randevu İptali'), ('test_result', 'Test Sonucu Bildirimi'), ('prescription', 'Reçete Bildirimi'), ('welcome', 'Hoş Geldiniz'), ('password_reset', 'Şifre Sıfırlama'), ('custom', 'Özel Şablon')], max_length=30, verbose_name='Şablon Tipi')),
                ('subject', models.CharField(max_length=200, verbose_name='E-posta Konusu')),
                ('content', models.TextField(help_text='HTML kullanabilirsiniz. Değişkenler için {{değişken_adı}} formatını kullanın.', verbose_name='E-posta İçeriği')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'E-posta Şablonu',
                'verbose_name_plural': 'E-posta Şablonları',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('report_type', models.CharField(choices=[('doctor_performance', 'Doktor Performans Raporu'), ('patient_statistics', 'Hasta İstatistikleri Raporu'), ('financial', 'Finansal Rapor'), ('appointment', 'Randevu Raporu'), ('treatment', 'Tedavi Raporu'), ('custom', 'Özel Rapor')], max_length=30, verbose_name='Rapor Tipi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('query', models.TextField(help_text='Bu şablonu kullanarak rapor oluşturulduğunda çalıştırılacak SQL sorgusu.', verbose_name='SQL Sorgusu')),
                ('columns', models.JSONField(default=list, help_text='Raporda gösterilecek sütunlar. JSON formatında: [{"name": "sütun_adı", "display": "Gösterim Adı"}]', verbose_name='Sütunlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
            },
        ),
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Tarih')),
                ('total_patients', models.IntegerField(default=0, verbose_name='Toplam Hasta Sayısı')),
                ('total_doctors', models.IntegerField(default=0, verbose_name='Toplam Doktor Sayısı')),
                ('total_appointments', models.IntegerField(default=0, verbose_name='Toplam Randevu Sayısı')),
                ('completed_appointments', models.IntegerField(default=0, verbose_name='Tamamlanan Randevu Sayısı')),
                ('cancelled_appointments', models.IntegerField(default=0, verbose_name='İptal Edilen Randevu Sayısı')),
                ('total_treatments', models.IntegerField(default=0, verbose_name='Toplam Tedavi Sayısı')),
                ('daily_active_users', models.IntegerField(default=0, verbose_name='Günlük Aktif Kullanıcı Sayısı')),
                ('data_json', models.JSONField(default=dict, help_text='Bu alana ekstra istatistik verilerini JSON formatında kaydedebilirsiniz.', verbose_name='Ek Veriler (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sistem İstatistiği',
                'verbose_name_plural': 'Sistem İstatistikleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.message', verbose_name='Üst Mesaj')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment', 'Randevu Bildirimi'), ('test_result', 'Test Sonucu Bildirimi'), ('prescription', 'Reçete Bildirimi'), ('message', 'Mesaj Bildirimi'), ('system', 'Sistem Bildirimi')], max_length=20, verbose_name='Bildirim Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('related_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rapor Adı')),
                ('parameters', models.JSONField(default=dict, help_text='Rapor oluşturulurken kullanılan parametreler. JSON formatında.', verbose_name='Parametreler')),
                ('result_data', models.JSONField(default=list, help_text='Rapor sonucu. JSON formatında.', verbose_name='Sonuç Verileri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Rapor Dosyası')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.reporttemplate', verbose_name='Rapor Şablonu')),
            ],
            options={
                'verbose_name': 'Oluşturulan Rapor',
                'verbose_name_plural': 'Oluşturulan Raporlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('appointment_count', models.IntegerField(default=0, verbose_name='Randevu Sayısı')),
                ('completed_appointment_count', models.IntegerField(default=0, verbose_name='Tamamlanan Randevu Sayısı')),
                ('treatment_count', models.IntegerField(default=0, verbose_name='Tedavi Sayısı')),
                ('prescription_count', models.IntegerField(default=0, verbose_name='Reçete Sayısı')),
                ('lab_test_count', models.IntegerField(default=0, verbose_name='Laboratuvar Testi Sayısı')),
                ('average_appointment_duration', models.FloatField(default=0.0, verbose_name='Ortalama Randevu Süresi (dakika)')),
                ('data_json', models.JSONField(default=dict, verbose_name='Ek Veriler (JSON)')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
            ],
            options={
                'verbose_name': 'Doktor İstatistiği',
                'verbose_name_plural': 'Doktor İstatistikleri',
                'ordering': ['-date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
