# Generated by Django 5.0.6 on 2024-12-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speciality",
            options={
                "ordering": ["name"],
                "verbose_name": "Speciality",
                "verbose_name_plural": "Specialities",
            },
        ),
        migrations.AddField(
            model_name="speciality",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="speciality",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
