# Generated by Django 5.1.7 on 2025-06-30 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userthemepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthemepreference',
            name='sidebar_mode',
            field=models.CharField(choices=[('light', 'Açık Kenar Çubuğu'), ('dark', 'Koyu Kenar Çubuğu')], default='light', max_length=20, verbose_name='Kenar Çubuğu Modu'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Açık Tema'), ('dark', 'Koyu Tema'), ('system', 'Sistem Teması')], default='light', max_length=20, verbose_name='Tema'),
        ),
    ]
