# Generated by Django 5.0.6 on 2025-08-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        default="Laso Digital Health", max_length=200
                    ),
                ),
                (
                    "hospital_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital/"
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(default="Bangladesh", max_length=100),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "accreditation",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "timezone",
                    models.CharField(default="Asia/Dhaka", max_length=50),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("%d/%m/%Y", "DD/MM/YYYY"),
                            ("%m/%d/%Y", "MM/DD/YYYY"),
                            ("%Y-%m-%d", "YYYY-MM-DD"),
                        ],
                        default="%d/%m/%Y",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12", "12 Hour"), ("24", "24 Hour")],
                        default="12",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=10)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("appointment_reminders", models.BooleanField(default=True)),
                ("reminder_hours_before", models.IntegerField(default=24)),
                ("monday_open", models.TimeField(default="09:00")),
                ("monday_close", models.TimeField(default="17:00")),
                ("tuesday_open", models.TimeField(default="09:00")),
                ("tuesday_close", models.TimeField(default="17:00")),
                ("wednesday_open", models.TimeField(default="09:00")),
                ("wednesday_close", models.TimeField(default="17:00")),
                ("thursday_open", models.TimeField(default="09:00")),
                ("thursday_close", models.TimeField(default="17:00")),
                ("friday_open", models.TimeField(default="09:00")),
                ("friday_close", models.TimeField(default="17:00")),
                ("saturday_open", models.TimeField(default="09:00")),
                ("saturday_close", models.TimeField(default="13:00")),
                ("sunday_closed", models.BooleanField(default=True)),
                (
                    "sunday_open",
                    models.TimeField(blank=True, default="09:00", null=True),
                ),
                (
                    "sunday_close",
                    models.TimeField(blank=True, default="17:00", null=True),
                ),
                ("max_appointments_per_day", models.IntegerField(default=50)),
                (
                    "appointment_duration",
                    models.IntegerField(
                        default=30, help_text="Duration in minutes"
                    ),
                ),
                ("allow_online_booking", models.BooleanField(default=True)),
                (
                    "require_payment_confirmation",
                    models.BooleanField(default=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Settings",
                "verbose_name_plural": "Hospital Settings",
            },
        ),
    ]
