# Generated by Django 5.0.6 on 2025-08-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_soap_notes_ehr_audit_log'),
        ('core', '0004_hospitalsettings'),
    ]

    operations = [
    ]