# Generated by Django 5.1.7 on 2025-08-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_communicationnotification_doctorperformancemetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorperformancemetric',
            options={'ordering': ['-date'], 'verbose_name': 'Doctor Performance Metric', 'verbose_name_plural': 'Doctor Performance Metrics'},
        ),
        migrations.AlterModelOptions(
            name='doctorstatistics',
            options={'ordering': ['-date'], 'verbose_name': 'Doctor Statistic', 'verbose_name_plural': 'Doctor Statistics'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification Log', 'verbose_name_plural': 'Notification Logs'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'Notification Template', 'verbose_name_plural': 'Notification Templates'},
        ),
        migrations.AlterModelOptions(
            name='systemstatistics',
            options={'ordering': ['-date'], 'verbose_name': 'System Statistic', 'verbose_name_plural': 'System Statistics'},
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='appointments_count',
            field=models.IntegerField(default=0, verbose_name='Appointments Count'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating (out of 5)'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='efficiency_score',
            field=models.FloatField(default=0.0, verbose_name='Efficiency Score (out of 100)'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='patient_satisfaction',
            field=models.FloatField(default=0.0, verbose_name='Patient Satisfaction (out of 100)'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='treatments_count',
            field=models.IntegerField(default=0, verbose_name='Treatments Count'),
        ),
        migrations.AlterField(
            model_name='doctorperformancemetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='appointment_count',
            field=models.IntegerField(default=0, verbose_name='Appointment Count'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='average_appointment_duration',
            field=models.FloatField(default=0.0, verbose_name='Average Appointment Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='completed_appointment_count',
            field=models.IntegerField(default=0, verbose_name='Completed Appointment Count'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='data_json',
            field=models.JSONField(default=dict, verbose_name='Extra Data (JSON)'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='lab_test_count',
            field=models.IntegerField(default=0, verbose_name='Lab Test Count'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='prescription_count',
            field=models.IntegerField(default=0, verbose_name='Prescription Count'),
        ),
        migrations.AlterField(
            model_name='doctorstatistics',
            name='treatment_count',
            field=models.IntegerField(default=0, verbose_name='Treatment Count'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent_via_email',
            field=models.BooleanField(default=False, verbose_name='Sent via Email?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent_via_sms',
            field=models.BooleanField(default=False, verbose_name='Sent via SMS?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_confirmed', 'Appointment Confirmed'), ('lab_result_ready', 'Lab Result Ready'), ('prescription_ready', 'Prescription Ready'), ('treatment_completed', 'Treatment Completed'), ('medication_reminder', 'Medication Reminder'), ('system_maintenance', 'System Maintenance'), ('doctor_schedule_change', 'Doctor Schedule Change'), ('emergency_alert', 'Emergency Alert')], max_length=30, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='delivery_method',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.notification', verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='appointment_reminder_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Appointment reminder hours (hours before)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_appointment_reminders',
            field=models.BooleanField(default=True, verbose_name='Appointment reminders (Email)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_lab_results',
            field=models.BooleanField(default=True, verbose_name='Lab results (Email)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_prescription_ready',
            field=models.BooleanField(default=True, verbose_name='Prescription ready (Email)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_system_updates',
            field=models.BooleanField(default=False, verbose_name='System updates (Email)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='medication_reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='Medication reminders enabled'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='medication_reminder_times',
            field=models.JSONField(default=list, help_text='In format: ["08:00", "12:00", "18:00"]', verbose_name='Medication reminder times'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_appointment_reminders',
            field=models.BooleanField(default=False, verbose_name='Appointment reminders (SMS)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_emergency_alerts',
            field=models.BooleanField(default=True, verbose_name='Emergency alerts (SMS)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='email_template',
            field=models.TextField(blank=True, help_text='Custom HTML template for email', verbose_name='Email Template (HTML)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='message_template',
            field=models.TextField(help_text='You can use Django template syntax', verbose_name='Message Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_confirmed', 'Appointment Confirmed'), ('lab_result_ready', 'Lab Result Ready'), ('prescription_ready', 'Prescription Ready'), ('treatment_completed', 'Treatment Completed'), ('medication_reminder', 'Medication Reminder'), ('system_maintenance', 'System Maintenance'), ('doctor_schedule_change', 'Doctor Schedule Change'), ('emergency_alert', 'Emergency Alert')], max_length=30, unique=True, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='sms_template',
            field=models.CharField(blank=True, help_text='Short text for SMS (max 160 characters)', max_length=160, verbose_name='SMS Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_template',
            field=models.CharField(help_text='You can use Django template syntax: {{ variable }}', max_length=200, verbose_name='Title Template'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='cancelled_appointments',
            field=models.IntegerField(default=0, verbose_name='Cancelled Appointments'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='completed_appointments',
            field=models.IntegerField(default=0, verbose_name='Completed Appointments'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='daily_active_users',
            field=models.IntegerField(default=0, verbose_name='Daily Active Users'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='data_json',
            field=models.JSONField(default=dict, help_text='You can store extra statistical data in JSON format in this field.', verbose_name='Extra Data (JSON)'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='total_appointments',
            field=models.IntegerField(default=0, verbose_name='Total Appointments'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='total_doctors',
            field=models.IntegerField(default=0, verbose_name='Total Doctors'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='total_patients',
            field=models.IntegerField(default=0, verbose_name='Total Patients'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='total_treatments',
            field=models.IntegerField(default=0, verbose_name='Total Treatments'),
        ),
        migrations.AlterField(
            model_name='systemstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
