# Generated by Django 5.2.3 on 2025-09-01 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctorperformancemetric_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oluşturulan Rapor', 'verbose_name_plural': 'Oluşturulan Raporlar'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': 'Rapor Şablonu', 'verbose_name_plural': 'Rapor Şablonları'},
        ),
        migrations.AlterField(
            model_name='communicationnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Rapor Adı'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Rapor oluşturulurken kullanılan parametreler. JSON formatında.', verbose_name='Parametreler'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Rapor Dosyası'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='result_data',
            field=models.JSONField(default=list, help_text='Rapor sonucu. JSON formatında.', verbose_name='Sonuç Verileri'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.reporttemplate', verbose_name='Rapor Şablonu'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='columns',
            field=models.JSONField(default=list, help_text='Raporda gösterilecek sütunlar. JSON formatında: [{"name": "sütun_adı", "display": "Gösterim Adı"}]', verbose_name='Sütunlar'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Şablon Adı'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='query',
            field=models.TextField(help_text='Bu şablonu kullanarak rapor oluşturulduğunda çalıştırılacak SQL sorgusu.', verbose_name='SQL Sorgusu'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('doctor_performance', 'Doktor Performans Raporu'), ('patient_statistics', 'Hasta İstatistikleri Raporu'), ('financial', 'Finansal Rapor'), ('appointment', 'Randevu Raporu'), ('treatment', 'Tedavi Raporu'), ('custom', 'Özel Rapor')], max_length=30, verbose_name='Rapor Tipi'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
