# Generated by Django 5.1.7 on 2025-09-08 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_generatedreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated Report', 'verbose_name_plural': 'Generated Reports'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': 'Report Template', 'verbose_name_plural': 'Report Templates'},
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Report Name'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Parameters used when generating the report. In JSON format.', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Report File'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='result_data',
            field=models.JSONField(default=list, help_text='Report result. In JSON format.', verbose_name='Result Data'),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.reporttemplate', verbose_name='Report Template'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='columns',
            field=models.JSONField(default=list, help_text='Columns to be displayed in the report. JSON format: [{"name": "column_name", "display": "Display Name"}]', verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='query',
            field=models.TextField(help_text='SQL query to be executed when generating a report using this template.', verbose_name='SQL Query'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('doctor_performance', 'Doctor Performance Report'), ('patient_statistics', 'Patient Statistics Report'), ('financial', 'Financial Report'), ('appointment', 'Appointment Report'), ('treatment', 'Treatment Report'), ('custom', 'Custom Report')], max_length=30, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='sidebar_mode',
            field=models.CharField(choices=[('light', 'Light Sidebar'), ('dark', 'Dark Sidebar')], default='light', max_length=20, verbose_name='Sidebar Mode'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('system', 'System Theme')], default='light', max_length=20, verbose_name='Theme'),
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login Session',
                'verbose_name_plural': 'Login Sessions',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='core_logins_user_id_79a554_idx'), models.Index(fields=['is_active', '-login_time'], name='core_logins_is_acti_f3416d_idx'), models.Index(fields=['ip_address', '-login_time'], name='core_logins_ip_addr_21245a_idx')],
            },
        ),
    ]
