# Generated by Django 5.1.7 on 2025-09-08 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_generatedreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this AI configuration', max_length=100, verbose_name='Configuration Name')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('huggingface', 'Hugging Face'), ('anthropic', 'Anthropic'), ('google', 'Google AI')], help_text='The AI service provider', max_length=20, verbose_name='AI Provider')),
                ('api_key', models.CharField(help_text='The API key for the AI service', max_length=500, verbose_name='API Key')),
                ('api_url', models.URLField(blank=True, help_text='Custom API URL (optional, for services like OpenRouter)', null=True, validators=[django.core.validators.URLValidator()], verbose_name='API URL')),
                ('model_name', models.CharField(blank=True, help_text='Specific model to use (e.g., gpt-4, claude-3, etc.)', max_length=100, null=True, verbose_name='Model Name')),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum number of tokens in the response', verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Controls randomness in responses (0.0 to 1.0)', verbose_name='Temperature')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active', verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default configuration to use', verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('symptom_analysis', 'Symptom Analysis'), ('drug_interaction', 'Drug Interaction Check'), ('general_health', 'General Health Advice'), ('medical_history', 'Medical History Analysis'), ('treatment_recommendation', 'Treatment Recommendation')], max_length=30, verbose_name='Template Type')),
                ('prompt_template', models.TextField(help_text='The prompt template with placeholders like {symptom}, {patient_age}, etc.', verbose_name='Prompt Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Template',
                'verbose_name_plural': 'AI Prompt Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique identifier for the conversation session', max_length=100, verbose_name='Session ID')),
                ('message', models.TextField(help_text='The message sent by the user', verbose_name='User Message')),
                ('response', models.TextField(help_text='The response from the AI', verbose_name='AI Response')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Number of tokens used for this interaction', verbose_name='Tokens Used')),
                ('response_time', models.FloatField(default=0.0, help_text='Time taken to generate the response (in seconds)', verbose_name='Response Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_config', models.ForeignKey(blank=True, help_text='The AI configuration used for this response', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aiconfiguration', verbose_name='AI Configuration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
