# Generated by Django 5.2.1 on 2025-06-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Drug Name')),
                ('active_ingredient', models.CharField(max_length=200, verbose_name='Active Ingredient')),
                ('drug_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Side Effects')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Contraindications')),
                ('is_prescription', models.BooleanField(default=True, verbose_name='Is it prescription?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Test Name')),
                ('test_details', models.TextField(blank=True, null=True, verbose_name='Test Details')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20, verbose_name='Status')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Requesting Doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='treatments.treatment', verbose_name='Treatment')),
            ],
            options={
                'verbose_name': 'Laboratory Test',
                'verbose_name_plural': 'Laboratory Tests',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('chronic', 'Chronic Disease'), ('surgery', 'Past Surgery'), ('allergy', 'Allergy'), ('medication', 'Regular Medication Use'), ('other', 'Other')], max_length=20, verbose_name='Condition Type')),
                ('condition_name', models.CharField(max_length=200, verbose_name='Condition Name/Description')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='Diagnosis Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Medical History Record',
                'verbose_name_plural': 'Medical History Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('xray', 'X-ray'), ('mri', 'MRI'), ('ct', 'CT (Computed Tomography)'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], max_length=20, verbose_name='Image Type')),
                ('body_part', models.CharField(max_length=100, verbose_name='Body Part')),
                ('image_file', models.ImageField(upload_to='medical_images/', verbose_name='Image File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('taken_date', models.DateField(verbose_name='Date Taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_medical_images', to=settings.AUTH_USER_MODEL, verbose_name='Requesting Doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='treatments.treatment', verbose_name='Treatment')),
            ],
            options={
                'verbose_name': 'Medical Image',
                'verbose_name_plural': 'Medical Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('diagnostic', 'Diagnostic Report'), ('progress', 'Progress Report'), ('discharge', 'Discharge Report'), ('consultation', 'Consultation Report'), ('sick_leave', 'Sick Leave Report'), ('other', 'Other')], max_length=20, verbose_name='Report Type')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('content', models.TextField(verbose_name='Report Content')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Report File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='written_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reporting Doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='treatments.treatment', verbose_name='Treatment')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.TextField(verbose_name='Result Text')),
                ('reference_values', models.TextField(blank=True, null=True, verbose_name='Reference Values')),
                ('is_normal', models.BooleanField(default=True, verbose_name='Is it normal?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('technician', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technician/Lab Assistant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/', verbose_name='Result File')),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='treatments.labtest', verbose_name='Laboratory Test')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Interaction Description')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, verbose_name='Severity')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('medication1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='treatments.medication', verbose_name='Drug 1')),
                ('medication2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='treatments.medication', verbose_name='Drug 2')),
            ],
            options={
                'verbose_name': 'Drug Interaction',
                'verbose_name_plural': 'Drug Interactions',
                'unique_together': {('medication1', 'medication2')},
            },
        ),
    ]
