# Generated by Django 5.2.1 on 2025-06-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İlaç Adı')),
                ('active_ingredient', models.CharField(max_length=200, verbose_name='Etken Madde')),
                ('drug_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlaç Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Yan Etkiler')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Kontrendikasyonlar')),
                ('is_prescription', models.BooleanField(default=True, verbose_name='Reçeteli mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'İlaç',
                'verbose_name_plural': 'İlaçlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Test Adı')),
                ('test_details', models.TextField(blank=True, null=True, verbose_name='Test Detayları')),
                ('status', models.CharField(choices=[('requested', 'Talep Edildi'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='requested', max_length=20, verbose_name='Durum')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='İstek Tarihi')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='İsteyen Doktor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='treatments.treatment', verbose_name='Tedavi')),
            ],
            options={
                'verbose_name': 'Laboratuvar Testi',
                'verbose_name_plural': 'Laboratuvar Testleri',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('chronic', 'Kronik Hastalık'), ('surgery', 'Geçirilmiş Ameliyat'), ('allergy', 'Alerji'), ('medication', 'Düzenli İlaç Kullanımı'), ('other', 'Diğer')], max_length=20, verbose_name='Durum Tipi')),
                ('condition_name', models.CharField(max_length=200, verbose_name='Durum Adı/Tanımı')),
                ('diagnosed_date', models.DateField(blank=True, null=True, verbose_name='Tanı Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ek Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Sağlık Geçmişi Kaydı',
                'verbose_name_plural': 'Sağlık Geçmişi Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('xray', 'Röntgen'), ('mri', 'MR'), ('ct', 'BT (Bilgisayarlı Tomografi)'), ('ultrasound', 'Ultrason'), ('other', 'Diğer')], max_length=20, verbose_name='Görüntü Tipi')),
                ('body_part', models.CharField(max_length=100, verbose_name='Vücut Bölgesi')),
                ('image_file', models.ImageField(upload_to='medical_images/', verbose_name='Görüntü Dosyası')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('taken_date', models.DateField(verbose_name='Çekim Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_medical_images', to=settings.AUTH_USER_MODEL, verbose_name='İsteyen Doktor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='treatments.treatment', verbose_name='Tedavi')),
            ],
            options={
                'verbose_name': 'Tıbbi Görüntü',
                'verbose_name_plural': 'Tıbbi Görüntüler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('diagnostic', 'Tanı Raporu'), ('progress', 'İlerleme Raporu'), ('discharge', 'Taburcu Raporu'), ('consultation', 'Konsültasyon Raporu'), ('sick_leave', 'İş Göremezlik Raporu'), ('other', 'Diğer')], max_length=20, verbose_name='Rapor Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Rapor Başlığı')),
                ('content', models.TextField(verbose_name='Rapor İçeriği')),
                ('valid_from', models.DateField(verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Sonu')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Rapor Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='written_reports', to=settings.AUTH_USER_MODEL, verbose_name='Raporu Yazan Doktor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='treatments.treatment', verbose_name='Tedavi')),
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.TextField(verbose_name='Sonuç Metni')),
                ('reference_values', models.TextField(blank=True, null=True, verbose_name='Referans Değerler')),
                ('is_normal', models.BooleanField(default=True, verbose_name='Normal mi?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('technician', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknisyen/Laborant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/', verbose_name='Sonuç Dosyası')),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='treatments.labtest', verbose_name='Laboratuvar Testi')),
            ],
            options={
                'verbose_name': 'Test Sonucu',
                'verbose_name_plural': 'Test Sonuçları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Etkileşim Açıklaması')),
                ('severity', models.CharField(choices=[('mild', 'Hafif'), ('moderate', 'Orta'), ('severe', 'Ciddi')], max_length=20, verbose_name='Şiddet')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Öneriler')),
                ('medication1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='treatments.medication', verbose_name='İlaç 1')),
                ('medication2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='treatments.medication', verbose_name='İlaç 2')),
            ],
            options={
                'verbose_name': 'İlaç Etkileşimi',
                'verbose_name_plural': 'İlaç Etkileşimleri',
                'unique_together': {('medication1', 'medication2')},
            },
        ),
    ]
