# Generated by Django 5.2.1 on 2025-06-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_medication_labtest_medicalhistory_medicalimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='treatments.medication', verbose_name='İlaç'),
        ),
    ]
