# Generated by Django 5.1.7 on 2025-08-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctortimeoff_doctoravailability'),
        ('treatments', '0003_prescription_medication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationinteraction',
            options={'verbose_name': 'Medication Interaction', 'verbose_name_plural': 'Medication Interactions'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterField(
            model_name='medication',
            name='active_ingredient',
            field=models.CharField(max_length=200, verbose_name='Active Ingredient'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Contraindications'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='drug_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug Code'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_prescription',
            field=models.BooleanField(default=True, verbose_name='Prescription Required?'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Side Effects'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='medicationinteraction',
            name='description',
            field=models.TextField(verbose_name='Interaction Description'),
        ),
        migrations.AlterField(
            model_name='medicationinteraction',
            name='medication1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='treatments.medication', verbose_name='Medication 1'),
        ),
        migrations.AlterField(
            model_name='medicationinteraction',
            name='medication2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='treatments.medication', verbose_name='Medication 2'),
        ),
        migrations.AlterField(
            model_name='medicationinteraction',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recommendations'),
        ),
        migrations.AlterField(
            model_name='medicationinteraction',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(verbose_name='Usage Instructions'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='treatments.medication', verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='treatments.treatment', verbose_name='Treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
