# Generated by Django 5.2.3 on 2025-09-01 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_alter_medication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='condition_name',
            field=models.CharField(max_length=200, verbose_name='Durum Adı/Tanımı'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='condition_type',
            field=models.CharField(choices=[('chronic', 'Kronik Hastalık'), ('surgery', 'Geçirilmiş Ameliyat'), ('allergy', 'Alerji'), ('medication', 'Düzenli İlaç Kullanımı'), ('other', 'Diğer')], max_length=20, verbose_name='Durum Tipi'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanı Tarihi'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ek Notlar'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL, verbose_name='Hasta'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='body_part',
            field=models.CharField(max_length=100, verbose_name='Body Region'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_normal',
            field=models.BooleanField(default=True, verbose_name='Is Normal?'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
