# Generated by Django 5.1.7 on 2025-09-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0005_alter_medicalhistory_condition_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='condition_name',
            field=models.CharField(max_length=200, verbose_name='Condition Name/Description'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='condition_type',
            field=models.CharField(choices=[('chronic', 'Chronic Disease'), ('surgery', 'Past Surgery'), ('allergy', 'Allergy'), ('medication', 'Regular Medication Use'), ('other', 'Other')], max_length=20, verbose_name='Condition Type'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Diagnosis Date'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
