# Generated by Django 5.1.7 on 2025-06-30 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Süre (dakika)')),
                ('status', models.CharField(choices=[('scheduled', 'Zamanlandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('no_show', 'Katılım Sağlanmadı')], default='scheduled', max_length=20, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Ana Şikayet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telemedicine_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Tele-tıp Randevusu',
                'verbose_name_plural': 'Tele-tıp Randevuları',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='TeleMedicineConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('video', 'Video Görüşme'), ('audio', 'Ses Görüşmesi'), ('chat', 'Metin Sohbeti'), ('hybrid', 'Karma (Video + Chat)')], default='video', max_length=20, verbose_name='Konsültasyon Türü')),
                ('status', models.CharField(choices=[('scheduled', 'Zamanlandı'), ('waiting', 'Bekleniyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('no_show', 'Katılım Sağlanmadı'), ('technical_issue', 'Teknik Sorun')], default='scheduled', max_length=20, verbose_name='Durum')),
                ('meeting_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Toplantı ID')),
                ('meeting_url', models.URLField(blank=True, help_text='Video konferans bağlantısı', verbose_name="Toplantı URL'si")),
                ('meeting_password', models.CharField(blank=True, max_length=50, verbose_name='Toplantı Şifresi')),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('internal', 'Internal System')], default='internal', max_length=50, verbose_name='Platform')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='Planlanan Başlangıç')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (Dakika)')),
                ('doctor_joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Doktor Katılım Zamanı')),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Hasta Katılım Zamanı')),
                ('connection_quality', models.CharField(blank=True, choices=[('excellent', 'Mükemmel'), ('good', 'İyi'), ('fair', 'Orta'), ('poor', 'Kötü')], max_length=20, verbose_name='Bağlantı Kalitesi')),
                ('technical_issues', models.TextField(blank=True, verbose_name='Teknik Sorunlar')),
                ('consultation_notes', models.TextField(blank=True, verbose_name='Konsültasyon Notları')),
                ('patient_feedback', models.TextField(blank=True, verbose_name='Hasta Geri Bildirimi')),
                ('doctor_feedback', models.TextField(blank=True, verbose_name='Doktor Geri Bildirimi')),
                ('patient_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Hasta Değerlendirmesi (1-5)')),
                ('doctor_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Doktor Değerlendirmesi (1-5)')),
                ('is_recorded', models.BooleanField(default=False, verbose_name='Kayıt Yapıldı mı?')),
                ('recording_url', models.URLField(blank=True, verbose_name="Kayıt URL'si")),
                ('shared_files', models.JSONField(blank=True, default=list, help_text='Konsültasyon sırasında paylaşılan dosya listesi', verbose_name='Paylaşılan Dosyalar')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Şifreli mi?')),
                ('waiting_room_enabled', models.BooleanField(default=True, verbose_name='Bekleme Odası Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_consultation', to='appointments.appointment', verbose_name='Randevu')),
            ],
            options={
                'verbose_name': 'Telemedicine Konsültasyonu',
                'verbose_name_plural': 'Telemedicine Konsültasyonları',
                'ordering': ['-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeleMedicineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_camera_enabled', models.BooleanField(default=True, verbose_name='Varsayılan Kamera Açık')),
                ('default_microphone_enabled', models.BooleanField(default=True, verbose_name='Varsayılan Mikrofon Açık')),
                ('video_quality', models.CharField(choices=[('low', 'Düşük (360p)'), ('medium', 'Orta (720p)'), ('high', 'Yüksek (1080p)')], default='medium', max_length=20, verbose_name='Video Kalitesi')),
                ('consultation_reminders', models.BooleanField(default=True, verbose_name='Konsültasyon Hatırlatmaları')),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15, verbose_name='Kaç Dakika Önce Hatırlat')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS Bildirimleri')),
                ('require_waiting_room', models.BooleanField(default=True, verbose_name='Bekleme Odası Zorunlu')),
                ('allow_recording', models.BooleanField(default=False, verbose_name='Kayıt İzni')),
                ('allow_file_sharing', models.BooleanField(default=True, verbose_name='Dosya Paylaşım İzni')),
                ('max_consultation_duration', models.PositiveIntegerField(default=60, verbose_name='Maksimum Konsültasyon Süresi (Dakika)')),
                ('auto_end_consultation', models.BooleanField(default=True, verbose_name='Otomatik Sonlandır')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_settings', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Telemedicine Ayarları',
                'verbose_name_plural': 'Telemedicine Ayarları',
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='Oda Adı')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (saniye)')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Kayıt URL')),
                ('connection_quality', models.CharField(blank=True, choices=[('excellent', 'Mükemmel'), ('good', 'İyi'), ('fair', 'Orta'), ('poor', 'Kötü')], max_length=20, null=True, verbose_name='Bağlantı Kalitesi')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='telemedicine.telemedicineappointment', verbose_name='Randevu')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Sonlandıran')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Başlatan')),
            ],
            options={
                'verbose_name': 'Video Oturumu',
                'verbose_name_plural': 'Video Oturumları',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TelemedPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.JSONField(help_text='İlaç listesi ve dozaj bilgileri', verbose_name='İlaçlar')),
                ('instructions', models.TextField(verbose_name='Talimatlar')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Süre (gün)')),
                ('is_renewable', models.BooleanField(default=False, verbose_name='Yenilenebilir mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='telemedicine.telemedicineappointment', verbose_name='Randevu')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_telemedicine_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Doktor')),
            ],
            options={
                'verbose_name': 'Tele-tıp Reçetesi',
                'verbose_name_plural': 'Tele-tıp Reçeteleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('note_type', models.CharField(choices=[('diagnosis', 'Teşhis'), ('treatment_plan', 'Tedavi Planı'), ('follow_up', 'Takip'), ('general', 'Genel Not')], default='general', max_length=50, verbose_name='Not Türü')),
                ('is_private', models.BooleanField(default=False, help_text='Özel notlar sadece doktor tarafından görülebilir', verbose_name='Özel Not mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='telemedicine.telemedicineappointment', verbose_name='Randevu')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_telemedicine_notes', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Tele-tıp Notu',
                'verbose_name_plural': 'Tele-tıp Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeleMedicineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Metin'), ('file', 'Dosya'), ('image', 'Görsel'), ('system', 'Sistem Mesajı')], default='text', max_length=20, verbose_name='Mesaj Türü')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('file_url', models.URLField(blank=True, verbose_name="Dosya URL'si")),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='telemedicine.telemedicineconsultation', verbose_name='Konsültasyon')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Telemedicine Mesajı',
                'verbose_name_plural': 'Telemedicine Mesajları',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('document_type', models.CharField(choices=[('lab_result', 'Laboratuvar Sonucu'), ('prescription', 'Reçete'), ('medical_image', 'Tıbbi Görüntü'), ('referral', 'Sevk'), ('other', 'Diğer')], max_length=50, verbose_name='Belge Türü')),
                ('file', models.FileField(upload_to='telemedicine/documents/', verbose_name='Dosya')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='telemedicine.telemedicineappointment', verbose_name='Randevu')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_telemedicine_documents', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Tele-tıp Belgesi',
                'verbose_name_plural': 'Tele-tıp Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
