# Generated by Django 5.1.7 on 2025-08-26 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctortimeoff_doctoravailability'),
        ('telemedicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemeddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telemedicine Document', 'verbose_name_plural': 'Telemedicine Documents'},
        ),
        migrations.AlterModelOptions(
            name='telemedicineappointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Telemedicine Appointment', 'verbose_name_plural': 'Telemedicine Appointments'},
        ),
        migrations.AlterModelOptions(
            name='telemedicineconsultation',
            options={'ordering': ['-scheduled_start_time'], 'verbose_name': 'Telemedicine Consultation', 'verbose_name_plural': 'Telemedicine Consultations'},
        ),
        migrations.AlterModelOptions(
            name='telemedicinemessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Telemedicine Message', 'verbose_name_plural': 'Telemedicine Messages'},
        ),
        migrations.AlterModelOptions(
            name='telemednote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telemedicine Note', 'verbose_name_plural': 'Telemedicine Notes'},
        ),
        migrations.AlterModelOptions(
            name='telemedprescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telemedicine Prescription', 'verbose_name_plural': 'Telemedicine Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='videosession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Video Session', 'verbose_name_plural': 'Video Sessions'},
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='telemedicine.telemedicineappointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='document_type',
            field=models.CharField(choices=[('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('medical_image', 'Medical Image'), ('referral', 'Referral'), ('other', 'Other')], max_length=50, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='file',
            field=models.FileField(upload_to='telemedicine/documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='telemeddocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_telemedicine_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='chief_complaint',
            field=models.TextField(blank=True, verbose_name='Chief Complaint'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telemedicine_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='telemedicineappointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Start'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_consultation', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='consultation_notes',
            field=models.TextField(blank=True, verbose_name='Consultation Notes'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('chat', 'Text Chat'), ('hybrid', 'Hybrid (Video + Chat)')], default='video', max_length=20, verbose_name='Consultation Type'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='doctor_feedback',
            field=models.TextField(blank=True, verbose_name='Doctor Feedback'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='doctor_joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doctor Join Time'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='doctor_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Doctor Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (Minutes)'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='is_encrypted',
            field=models.BooleanField(default=True, verbose_name='Encrypted?'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='is_recorded',
            field=models.BooleanField(default=False, verbose_name='Recording Made?'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='meeting_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Meeting ID'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meeting Password'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Video conference link', verbose_name='Meeting URL'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='patient_feedback',
            field=models.TextField(blank=True, verbose_name='Patient Feedback'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='patient_joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Patient Join Time'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='patient_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Patient Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='recording_url',
            field=models.URLField(blank=True, verbose_name='Recording URL'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='scheduled_start_time',
            field=models.DateTimeField(verbose_name='Scheduled Start'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='shared_files',
            field=models.JSONField(blank=True, default=list, help_text='List of files shared during the consultation', verbose_name='Shared Files'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='technical_issues',
            field=models.TextField(blank=True, verbose_name='Technical Issues'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='waiting_room_enabled',
            field=models.BooleanField(default=True, verbose_name='Waiting Room Active'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='telemedicine.telemedicineconsultation', verbose_name='Consultation'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='file_url',
            field=models.URLField(blank=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read?'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System Message')], default='text', max_length=20, verbose_name='Message Type'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='telemedicinemessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='allow_recording',
            field=models.BooleanField(default=False, verbose_name='Recording Permission'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='consultation_reminders',
            field=models.BooleanField(default=True, verbose_name='Consultation Reminders'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='default_camera_enabled',
            field=models.BooleanField(default=True, verbose_name='Default Camera Enabled'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='default_microphone_enabled',
            field=models.BooleanField(default=True, verbose_name='Default Microphone Enabled'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=15, verbose_name='Remind Minutes Before'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='require_waiting_room',
            field=models.BooleanField(default=True, verbose_name='Waiting Room Required'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='video_quality',
            field=models.CharField(choices=[('low', 'Low (360p)'), ('medium', 'Medium (720p)'), ('high', 'High (1080p)')], default='medium', max_length=20, verbose_name='Video Quality'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='telemedicine.telemedicineappointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private notes can only be seen by the doctor', verbose_name='Private Note?'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='note_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('treatment_plan', 'Treatment Plan'), ('follow_up', 'Follow-up'), ('general', 'General Note')], default='general', max_length=50, verbose_name='Note Type'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='telemedicine.telemedicineappointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_telemedicine_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescribing Doctor'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='instructions',
            field=models.TextField(verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='is_renewable',
            field=models.BooleanField(default=False, verbose_name='Renewable?'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='medications',
            field=models.JSONField(help_text='List of medications and dosage information', verbose_name='Medications'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='telemedicine.telemedicineappointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='connection_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True, verbose_name='Connection Quality'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ended By'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='Recording URL'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='room_name',
            field=models.CharField(max_length=255, verbose_name='Room Name'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Started By'),
        ),
    ]
