# Generated by Django 5.2.3 on 2025-09-01 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0003_add_notes_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemedicineconsultation',
            name='shared_files',
            field=models.JSONField(blank=True, default=list, help_text='List of files shared during consultation', verbose_name='Shared Files'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='allow_file_sharing',
            field=models.BooleanField(default=True, verbose_name='File Sharing Permission'),
        ),
        migrations.AlterField(
            model_name='telemedicinesettings',
            name='auto_end_consultation',
            field=models.BooleanField(default=True, verbose_name='Auto End'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_telemedicine_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='telemednote',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private notes can only be viewed by the doctor', verbose_name='Private Note?'),
        ),
        migrations.AlterField(
            model_name='telemedprescription',
            name='medications',
            field=models.JSONField(help_text='Medication list and dosage information', verbose_name='Medications'),
        ),
    ]
