# Generated by Django 5.1.7 on 2025-09-27 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0004_alter_telemedicineconsultation_shared_files_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Attachment'), ('image', 'Image'), ('voice', 'Voice Message'), ('video_call_request', 'Video Call Request'), ('audio_call_request', 'Audio Call Request'), ('system', 'System Message')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='telemedicine/messages/', verbose_name='File Attachment')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent Message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('call_session_id', models.UUIDField(blank=True, null=True, verbose_name='Call Session ID')),
                ('call_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('missed', 'Missed'), ('completed', 'Completed')], max_length=20, null=True, verbose_name='Call Status')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_patient_messages', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_doctor_messages', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Doctor-Patient Message',
                'verbose_name_plural': 'Doctor-Patient Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'patient', '-created_at'], name='telemedicin_doctor__91d846_idx'), models.Index(fields=['is_read', '-created_at'], name='telemedicin_is_read_f439b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Last Message At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('doctor_unread_count', models.PositiveIntegerField(default=0, verbose_name='Doctor Unread Count')),
                ('patient_unread_count', models.PositiveIntegerField(default=0, verbose_name='Patient Unread Count')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_message_threads', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_message_threads', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Message Thread',
                'verbose_name_plural': 'Message Threads',
                'ordering': ['-last_message_at'],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
