# Generated by Django 5.2.1 on 2025-06-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('start_time', models.TimeField(blank=True, help_text='Eğer tam gün izin değilse', null=True, verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(blank=True, help_text='Eğer tam gün izin değilse', null=True, verbose_name='Bitiş Saati')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='İzin Sebebi')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Tam Gün mü?')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
            ],
            options={
                'verbose_name': 'Doktor İzni',
                'verbose_name_plural': 'Doktor İzinleri',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın Günü')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
            ],
            options={
                'verbose_name': 'Doktor Uygunluğu',
                'verbose_name_plural': 'Doktor Uygunlukları',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('doctor', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
