# Generated by Django 5.0.6 on 2025-08-08 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("api", "API Services"),
                            ("storage", "Storage"),
                            ("cache", "Cache"),
                            ("queue", "Queue"),
                            ("overall", "Overall System"),
                        ],
                        max_length=50,
                        verbose_name="Check Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="healthy",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Details"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        default=0.0, verbose_name="Response Time (ms)"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Checked At"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("patient_data", "Patient Data"),
                            ("doctor_data", "Doctor Data"),
                            ("appointment_data", "Appointment Data"),
                            ("prescription_data", "Prescription Data"),
                            ("vital_data", "Vital Signs Data"),
                            ("hospital_data", "Hospital Data"),
                            ("full_sync", "Full System Sync"),
                        ],
                        max_length=50,
                        verbose_name="Sync Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Records Processed"
                    ),
                ),
                (
                    "records_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Records Failed"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_syncs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Status",
                "verbose_name_plural": "Sync Status",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        max_length=100, verbose_name="Entity Type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=100, verbose_name="Entity ID"),
                ),
                (
                    "action",
                    models.CharField(max_length=50, verbose_name="Action"),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="Success"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "sync_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sync_monitor.syncstatus",
                        verbose_name="Sync Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Sync Log",
                "verbose_name_plural": "Data Sync Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
