# Generated by Django 5.0.6 on 2025-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_delete_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="year_of_completion",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
