# Generated by Django 5.0.6 on 2025-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_education_year_of_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="from_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="to_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
